"""Python API for pyling."""
from __future__ import annotations

from .engine import INFERENCE_FUSE_EXIT_CODE, InferenceFuseError, ReasonStreamResult, reason, reason_stream, run_async, reason_message_stream
from .builtins import register_builtin, unregister_builtin, register_builtin_module, list_builtin_iris
from .store import MemoryFactStore, PersistentFactStore, create_fact_store
from .terms import (
    Blank,
    GraphTerm,
    Iri,
    ListTerm,
    Literal,
    OpenListTerm,
    PrefixEnv,
    Rule,
    Term,
    Triple,
    Var,
    RDF_NS,
    RDFS_NS,
    OWL_NS,
    XSD_NS,
    MATH_NS,
    LIST_NS,
    LOG_NS,
    STRING_NS,
    CRYPTO_NS,
    DT_NS,
    term_from_primitive,
    triple_from_primitive,
    rule_from_primitive,
    term_to_primitive,
    triple_to_primitive,
    rule_to_primitive,
)
from .parser import N3SyntaxError, parse_n3, parse_sources
from .rdf import RdfSyntaxError, parse_rdf_text, parse_rdf_message_log, iter_rdf_message_documents, assert_rdf12_surface_syntax
from .printing import term_to_n3, triple_to_n3, triples_to_n3

__all__ = [
    "reason",
    "reason_stream",
    "run_async",
    "reason_message_stream",
    "ReasonStreamResult",
    "InferenceFuseError",
    "INFERENCE_FUSE_EXIT_CODE",
    "register_builtin",
    "unregister_builtin",
    "register_builtin_module",
    "list_builtin_iris",
    "create_fact_store",
    "MemoryFactStore",
    "PersistentFactStore",
    "Iri",
    "Literal",
    "Var",
    "Blank",
    "ListTerm",
    "OpenListTerm",
    "GraphTerm",
    "Triple",
    "Rule",
    "PrefixEnv",
    "Term",
    "parse_n3",
    "parse_sources",
    "N3SyntaxError",
    "RdfSyntaxError",
    "parse_rdf_text",
    "parse_rdf_message_log",
    "iter_rdf_message_documents",
    "assert_rdf12_surface_syntax",
    "term_to_n3",
    "triple_to_n3",
    "triples_to_n3",
    "term_from_primitive",
    "triple_from_primitive",
    "rule_from_primitive",
    "term_to_primitive",
    "triple_to_primitive",
    "rule_to_primitive",
]
